---
title: "data wrangling ex1"
author: "sasiratkitt"
date: "August 22, 2018"
output: html_document
---

```{r load package}
library(dplyr)
```


```{r load data, include=FALSE}
setwd("~/R Projects/springboard_datascience_r/data_wrangling")
refine <- read.csv("refine.csv", stringsAsFactors = FALSE)
```

```{r clean up brand names}
refine <- refine0 
refine$company <- tolower(refine0$company)

#correct the company names
company <- c(unique(refine$company))
correction <- c(rep("philips",4), rep("akzo",3), rep("philips",2), "van houten", rep("unilever",2))
company_correct <- data_frame(company, correction)
refine <- refine %>% left_join(company_correct, by = "company")

refine <- rename(refine, company_old = company)
refine <- rename(refine, company = correction)
#refine <- rename(refine, c("company_old" = "company", "company" = "correction"))

```

```{r separate string}
refine <- refine %>% separate(Product.code...number,into = c("product_code","product_name"),sep = "-")
```

```{r product category mapping}
product_code <- c("p","v","x", "q")
product_category <-  c("Smartphone", "TV", "Laptop", "Tablet")
category <- data_frame(product_code, product_category)

refine <- refine %>% left_join(category, by = "product_code")
```

```{r address}
refine$full_address <- paste(refine$address, refine$city, refine$country, sep = ",")
```

```{r dummy}

dummy_company <- dummy(refine$company)
dummy_product <- dummy(refine$product_category)

refine <- cbind(refine,dummy_company, dummy_product)
```

```{r write}
write.csv(refine,"refine_clean.csv", row.names = FALSE)
```



